// <auto-generated />
using BusinessLogic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessLogic.Migrations
{
    [DbContext(typeof(DepositContext))]
    partial class DepositContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BusinessLogic.Models.Deposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MaxTermMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MinTermMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Deposits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankName = "Bank A",
                            Currency = "BGN",
                            InterestRate = 1.5m,
                            MaxAmount = 100000m,
                            MaxTermMonths = 6,
                            MinAmount = 5000m,
                            MinTermMonths = 6,
                            Name = "Standard 6-Month",
                            TaxRate = 10m
                        },
                        new
                        {
                            Id = 2,
                            BankName = "Bank B",
                            Currency = "BGN",
                            InterestRate = 2.0m,
                            MaxAmount = 50000m,
                            MaxTermMonths = 12,
                            MinAmount = 1000m,
                            MinTermMonths = 12,
                            Name = "Variable 12-Month",
                            TaxRate = 10m
                        },
                        new
                        {
                            Id = 3,
                            BankName = "Bank C",
                            Currency = "EUR",
                            InterestRate = 1.8m,
                            MaxAmount = 200000m,
                            MaxTermMonths = 24,
                            MinAmount = 2000m,
                            MinTermMonths = 24,
                            Name = "Long-Term 24-Month",
                            TaxRate = 10m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
